// "One scenario, two executions": compile the simulation scenario into a k6 script (arrival-rate executors)
// and a fault plan for Toxiproxy, so the same file drives a real load test on a staging environment.

import { peakRps, rpsAt } from './parse';
import type { Model, Scenario } from './types';

export interface K6Options {
  /** hard cap on request rate; the script refuses to start if the scenario exceeds it */
  maxRps?: number;
  /** hosts the script may target; BASE_URL must match one of them */
  allowHosts?: string[];
}

function stages(sc: Scenario): { target: number; duration: string }[] {
  const p = sc.traffic;
  const sec = (ms: number) => `${Math.max(1, Math.round(ms / 1000))}s`;
  switch (p.type) {
    case 'constant':
      return [];
    case 'ramp':
      return [
        ...(p.start > 0 ? [{ target: Math.round(p.from), duration: sec(p.start) }] : []),
        { target: Math.round(p.to), duration: sec(p.end - p.start) },
        ...(sc.duration > p.end ? [{ target: Math.round(p.to), duration: sec(sc.duration - p.end) }] : []),
      ];
    case 'spike': {
      const out = [{ target: Math.round(p.base), duration: sec(p.at) }];
      out.push({ target: Math.round(p.peak), duration: sec(Math.max(1000, p.rampUp)) });
      const holdEnd = Math.min(sc.duration, p.at + p.rampUp + p.hold);
      out.push({ target: Math.round(p.peak), duration: sec(holdEnd - p.at - p.rampUp) });
      if (holdEnd < sc.duration) {
        out.push({ target: Math.round(p.base), duration: '1s' });
        out.push({ target: Math.round(p.base), duration: sec(sc.duration - holdEnd) });
      }
      return out;
    }
    case 'steps': {
      const out: { target: number; duration: string }[] = [];
      const pts = [...p.steps, { at: sc.duration, rps: rpsAt(p, sc.duration) }];
      for (let i = 0; i < pts.length - 1; i++) {
        out.push({ target: Math.round(pts[i].rps), duration: '1s' });
        out.push({ target: Math.round(pts[i].rps), duration: sec(pts[i + 1].at - pts[i].at) });
      }
      return out;
    }
  }
}

export function compileK6(model: Model, opts: K6Options = {}): string {
  const sc = model.scenario;
  const peak = peakRps(sc.traffic);
  const maxRps = opts.maxRps ?? Math.ceil(peak);
  const allow = opts.allowHosts ?? ['localhost', '127.0.0.1', 'staging'];
  const p50Guess = 0.2; // seconds in flight per request, used only to pre-allocate VUs
  const vus = Math.max(10, Math.ceil(peak * p50Guess));
  const st = stages(sc);
  const executor =
    sc.traffic.type === 'constant'
      ? `{
      executor: 'constant-arrival-rate',
      rate: ${Math.round(sc.traffic.rps)},
      timeUnit: '1s',
      duration: '${Math.round(sc.duration / 1000)}s',
      preAllocatedVUs: ${vus},
      maxVUs: ${vus * 4},
    }`
      : `{
      executor: 'ramping-arrival-rate',
      startRate: ${Math.round(rpsAt(sc.traffic, 0))},
      timeUnit: '1s',
      preAllocatedVUs: ${vus},
      maxVUs: ${vus * 4},
      stages: ${JSON.stringify(st, null, 2).replace(/\n/g, '\n      ')},
    }`;
  const mix = sc.mix.map((m) => {
    const [method, ...rest] = m.ref.op.split(' ');
    const path = rest.join(' ') || '/';
    return { method: /^[A-Z]+$/.test(method) ? method : 'GET', path: /^[A-Z]+$/.test(method) ? path : m.ref.op, weight: +m.weight.toFixed(4), service: m.ref.node };
  });
  const thresholds: Record<string, unknown[]> = {
    http_req_duration: [{ threshold: `p(99)<${Math.round(sc.slo.p99)}`, abortOnFail: false }],
    http_req_failed: [{ threshold: `rate<${sc.slo.errorRate}`, abortOnFail: true, delayAbortEval: '10s' }],
  };
  for (const [id, s] of Object.entries(sc.slo.endpoints)) {
    const op = id.slice(id.indexOf(':') + 1);
    thresholds[`http_req_duration{api:${op}}`] = [`p(99)<${Math.round(s.p99)}`];
  }

  return `// Generated by load-simulator from the same scenario used for simulation.
// Run against an allow-listed staging environment only:
//   BASE_URL=http://staging.internal:8080 k6 run script.js
import http from 'k6/http';

const ALLOW_HOSTS = ${JSON.stringify(allow)};
const MAX_RPS = ${maxRps};
const PEAK_RPS = ${Math.ceil(peak)};
const BASE_URL = __ENV.BASE_URL;

if (!BASE_URL) throw new Error('BASE_URL is required');
const host = BASE_URL.replace(/^https?:\\/\\//, '').split(/[:/]/)[0];
if (!ALLOW_HOSTS.some((h) => host === h || host.includes(h))) {
  throw new Error(\`target "\${host}" is not in the allow list \${JSON.stringify(ALLOW_HOSTS)}\`);
}
if (/(^|[.-])prod/.test(host) && __ENV.I_KNOW_THIS_IS_PRODUCTION !== 'yes') {
  throw new Error('refusing to load-test what looks like a production host');
}
if (PEAK_RPS > MAX_RPS) throw new Error(\`scenario peak \${PEAK_RPS} RPS exceeds MAX_RPS \${MAX_RPS}\`);

const MIX = ${JSON.stringify(mix, null, 2)};

export const options = {
  discardResponseBodies: true,
  summaryTrendStats: ['avg', 'min', 'med', 'p(95)', 'p(99)', 'max'],
  scenarios: {
    traffic: ${executor},
  },
  thresholds: ${JSON.stringify(thresholds, null, 2).replace(/\n/g, '\n  ')},
};

function pick() {
  let u = Math.random();
  for (const m of MIX) {
    if ((u -= m.weight) < 0) return m;
  }
  return MIX[MIX.length - 1];
}

function fill(path) {
  return path.replace(/\\{[^}]+\\}/g, () => String(1 + Math.floor(Math.random() * 1000)));
}

export default function () {
  const m = pick();
  const body = m.method === 'GET' || m.method === 'DELETE' ? null : '{}';
  http.request(m.method, BASE_URL + fill(m.path), body, {
    headers: { 'Content-Type': 'application/json' },
    timeout: '${Math.round(sc.clientTimeout / 1000)}s',
    tags: { api: \`\${m.method} \${m.path}\` },
  });
}
`;
}

export interface FaultStep {
  at: number;
  until: number;
  target: string;
  /** Toxiproxy toxics to add for the duration */
  toxics: { type: 'latency' | 'timeout' | 'limit_data' | 'slicer'; attributes: Record<string, number> }[];
  /** tc netem equivalent for packet loss */
  netem?: string;
  note: string;
}

/**
 * Translate scenario faults into Toxiproxy toxics / tc netem commands.
 * Toxiproxy cannot multiply latency, so latencyX is converted with the target's typical latency (p50) when known.
 */
export function faultPlan(model: Model): FaultStep[] {
  return model.scenario.faults.map((f) => {
    const toxics: FaultStep['toxics'] = [];
    const notes: string[] = [];
    const node = model.nodes[f.target];
    if (f.latencyX !== 1) {
      let base = 10;
      if (node?.kind === 'db') {
        const q = Object.values(node.queries)[0]?.latency ?? node.defaultQuery.latency;
        base = q.kind === 'lognormal' ? Math.exp(q.mu) : q.kind === 'const' ? q.value : 10;
      } else if (node?.kind === 'external') base = node.latency.kind === 'lognormal' ? Math.exp(node.latency.mu) : 50;
      const extra = Math.round(base * (f.latencyX - 1));
      toxics.push({ type: 'latency', attributes: { latency: extra, jitter: Math.round(extra * 0.2) } });
      notes.push(`지연 ×${f.latencyX} ≈ +${extra}ms`);
    }
    if (f.down) {
      toxics.push({ type: 'timeout', attributes: { timeout: 0 } });
      notes.push('단절');
    }
    if (f.errorRate > 0) notes.push(`오류율 ${(f.errorRate * 100).toFixed(1)}%는 Toxiproxy로 표현할 수 없어 애플리케이션 장애 주입(예: Chaos Monkey for Spring Boot)이 필요합니다`);
    return {
      at: f.at,
      until: f.until,
      target: f.target,
      toxics,
      netem: f.loss > 0 ? `tc qdisc add dev eth0 root netem loss ${(f.loss * 100).toFixed(2)}%` : undefined,
      note: notes.join(', '),
    };
  });
}
