CREATE DATABASE IF NOT EXISTS orders;
CREATE DATABASE IF NOT EXISTS payments;
CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'app';
GRANT ALL ON orders.* TO 'app'@'%';
GRANT ALL ON payments.* TO 'app'@'%';

USE orders;
CREATE TABLE products (id INT PRIMARY KEY, name VARCHAR(64) NOT NULL);
CREATE TABLE stock (sku INT PRIMARY KEY, quantity INT NOT NULL);
CREATE TABLE orders (id BIGINT AUTO_INCREMENT PRIMARY KEY, amount BIGINT NOT NULL, items INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
SET SESSION cte_max_recursion_depth = 2000;
INSERT INTO products (id, name) WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 1000) SELECT n, CONCAT('product-', n) FROM seq;
INSERT INTO stock (sku, quantity) WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 1000) SELECT n, 100 + (n % 50) FROM seq;

USE payments;
CREATE TABLE payments (id BIGINT AUTO_INCREMENT PRIMARY KEY, amount BIGINT NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ledger (id BIGINT AUTO_INCREMENT PRIMARY KEY, event VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
